Fixes

diff --git a/src/lib/casetools-0.17/cases b/src/lib/casetools-0.17/cases
--- a/src/lib/casetools-0.17/cases
+++ b/src/lib/casetools-0.17/cases
@@ -39,37 +39,81 @@ cases::list() {
                 continue
             fi
 
-            echo "${_case}" | url::decode
+            cases::label_to_name "${_case}"
         done | sort
     fi
 }
 
-cases::case() {
-    local _case="${CASETOOLS_CASE}"
+cases::label_to_name() {
+    echo "${1}" | url::decode
+}
 
+cases::name_to_label() {
+    echo "${1}" | url::encode
+}
+
+cases::current() {
     if [ -z "${CASETOOLS_CASE}" ]
     then
         logging::fatal "No individual case has been selected"
     else
-        echo "${_case}" | url::decode
+        echo "${CASETOOLS_CASE}"
     fi
 }
 
-cases::selected() {
-    local _folder="${CASETOOLS_BASE}/${CASETOOLS_CASE}"
+cases::case() {
+    cases::label_to_name "$(cases::current)"
+}
 
-    if [ -z "${CASETOOLS_BASE}" ]
+cases::project_to_folder() {
+    local _project
+    local _label
+
+    if ! _project="${1:?Need a project name}"
+    then
+        logging::error "No project provided"
+        return 255
+    elif ! _label="$(cases::name_to_label "${_project}")"
+    then
+        logging::error "Can't convert project to label"
+        return 255
+    else
+        cases::label_to_folder "${_label}"
+    fi
+}
+
+cases::label_to_folder() {
+    local _folder
+    local _label
+
+    if ! _label="${1:?Need a project label}"
+    then
+        logging::error "No project label provided"
+        return 255
+    elif [ -z "${CASETOOLS_BASE}" ]
     then
         logging::fatal "No Cases home domain has been selected"
-    elif [ -z "${CASETOOLS_CASE}" ]
+        return 255
+    elif ! _folder="${CASETOOLS_BASE}/${_label}"
     then
-        logging::fatal "No individual case has been selected"
+        logging::error "Can't convert project to label"
+        return 255
     elif [ ! -d "${_folder}" ]
     then
         logging::error "Case folder '${_folder}' is missing"
         return 255
     else
         echo "${_folder}"
+    fi
+}
+
+cases::selected() {
+    if [ -z "${CASETOOLS_CASE}" ]
+    then
+        logging::fatal "No individual case has been selected"
+        return 255
+    else
+        cases::label_to_folder "${CASETOOLS_CASE}"
     fi
 }
 
diff --git a/src/lib/casetools-0.17/notebooks b/src/lib/casetools-0.17/notebooks
--- a/src/lib/casetools-0.17/notebooks
+++ b/src/lib/casetools-0.17/notebooks
@@ -8,25 +8,23 @@ local_path="$(dirname "${actual_name}")"
 #              Handle installing/removing projects from Jupyterlab
 #===================================================================================
 cases::notebooks::install_project_kernel() {
-    local _project
-    local _where
     local _installer_filename
+    local _project
+    local _label
 
     if ! _project="${1:?Need a project name}"
     then
         logging::error "No project provided"
         return 255
-    elif ! _where="$(casetool --case="${_project}" --where)"
+    elif ! _label="$(cases::notebooks::get_project_kernel_name "${_project}")"
     then
-        logging::error "No such project '${_project}'"
+        logging::error "Can't get label for '${_project}'"
         return 255
     elif ! _installer_filename="$(mktemp)"
     then
         logging::error "Failed creating temporary scriptfile"
         return 255
     fi
-
-    local _label="$(basename "${_where}" | sed -e 's/[\%][0-9][0-9]/_/g' | tr "[A-Z]" "[a-z]")"
 
     sed -e 's/^        //g' > "${_installer_filename}" <<< "
         easy_install pip==9.0.1 &&
@@ -45,20 +43,57 @@ cases::notebooks::install_project_kernel() {
     return ${_status}
 }
 
-cases::notebooks::remove_project_kernel() {
-    local _project
+cases::notebooks::get_project_kernel_name() {
     local _where
+
+    if ! _where="$(cases::project_to_folder "${1}")"
+    then
+        logging::error "No project provided"
+        return 255
+    fi
+
+    basename "${_where}" |
+    sed -e 's/[\%][0-9][0-9]/_/g' |
+    tr "[A-Z]" "[a-z]"
+}
+
+cases::notebooks::get_kernels_folder() {
+    echo "${HOME}/.local/share/jupyter/kernels"
+}
+
+cases::notebooks::remove_project_kernel() {
+    local _kernels_folder="$(cases::notebooks::get_kernels_folder)"
+    local _project
+    local _label
 
     if ! _project="${1:?Need a project name}"
     then
         logging::error "No project provided"
         return 255
-    elif ! _where="$(casetool --case="${_project}" --where)"
+    elif ! _label="$(cases::notebooks::get_project_kernel_name "${_project}" 2>/dev/null)"
     then
-        logging::error "No such project '${_project}'"
+        logging::error "Can't get label for '${_project}'"
         return 255
+    else
+        rm -rf "${_kernels_folder}/${_label}"
     fi
+}
 
-    local _label="$(basename "${_where}" | sed -e 's/[\%][0-9][0-9]/_/g' | tr "[A-Z]" "[a-z]")"
-    rm -rf "${HOME}/.local/share/jupyter/kernels/${_label}"
+cases::notebooks::get_installed_projects() {
+    local _kernels_folder="$(cases::notebooks::get_kernels_folder)"
+    local _project
+    local _label
+
+    cases::list all | while read _project
+    do
+        if ! _label="$(cases::notebooks::get_project_kernel_name "${_project}")"
+        then
+            :
+        elif [ ! -d "${_kernels_folder}/${_label}" ]
+        then
+            :
+        else
+            echo "${_project} (${_label})"
+        fi
+    done
 }
