Use new modules::install

diff --git a/src/lib/casetools-0.06/cases b/src/lib/casetools-0.06/cases
--- a/src/lib/casetools-0.06/cases
+++ b/src/lib/casetools-0.06/cases
@@ -8,11 +8,10 @@ cases::module() {
     local _folder="$(cases::selected)"
     local _url="${1}"
 
-    if modules::install::git "${_url}" "${CASETOOLS_CASE}" || modules::install::git "${_url}" master
+    if ! (modules::install "${_url}" "${CASETOOLS_CASE}" || modules::install::git "${_url}")
     then
-        :
-    else
-        logging::fatal "Cannot install required module '${_url}'"
+        logging::error "Cannot install required module '${_url}'"
+        return 255
     fi
 
     # Update requirements file
